config:
  send_anonymous_usage_stats: false

Raza_Hotel:        # this is your profile name
  target: dev
  outputs: 
    dev:
      type: snowflake
      account: KI58349_BUWBQIX-SQ09763
      user: RAZAHUSSAIN
      password: "Raaz{123456789"
      role: ACCOUNTADMIN         # optional
      database: HOTEL_DB
      schema: DBT_DEV            # only schema name
      warehouse: PC_DBT_WH       # must exist and be active