my_new_project:
  target: dev
  outputs: 
    dev:
      type: snowflake
      account: KI58349_BUWBQIX-SQ09763
      user: RAZAHUSSAIN
      password: Raaz{123456789
      role: ACCOUNTADMIN         # optional
      database: HOTEL_DB
      schema: HOTEL_DB.DBT_DEV             # or your schema
      warehouse: PC_DBT_WH      # <-- must be set
